splash = false

wallpaper {
    monitor = HDMI-A-1
    path = ~/graphics/wallpapers/bevel-spheres-reorg.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/graphics/wallpapers/arch-bevel-sphere-5120x2880-blur-2.jpeg
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/graphics/wallpapers/arch-bevel-sphere-5120x2880-blur.jpeg
    fit_mode = cover
}
