;; post-init.el --- Loaded after init -*- no-byte-compile: t; lexical-binding: t; -*-
;; WARNING: This file was generated by tangling a literate program.
;;          Do not edit this file, edit the source (emacs-init.org)!

(add-to-list 'load-path (expand-file-name "site-lisp/" minimal-emacs-user-directory))

(use-package compile-angel
  :ensure t
  :demand t
  :custom
  ;; Set `compile-angel-verbose` to nil to suppress output from compile-angel.
  ;; Drawback: The minibuffer will not display compile-angel's actions.
  (compile-angel-verbose nil)
  :config
  ;; The following directive prevents compile-angel from compiling your init
  ;; files. If you choose to remove this push to `compile-angel-excluded-files'
  ;; and compile your pre/post-init files, ensure you understand the
  ;; implications and thoroughly test your code. For example, if you're using
  ;; `use-package', you'll need to explicitly add `(require 'use-package)` at
  ;; the top of your init file.
  (push "/pre-init.el" compile-angel-excluded-files)
  (push "/post-init.el" compile-angel-excluded-files)
  (push "/pre-early-init.el" compile-angel-excluded-files)
  (push "/post-early-init.el" compile-angel-excluded-files)

  ;; A local mode that compiles .el files whenever the user saves them.
  ;; (add-hook 'emacs-lisp-mode-hook #'compile-angel-on-save-local-mode)

  ;; A global mode that compiles .el files before they are loaded.
  (compile-angel-on-load-mode))

(require 'server)
(unless (server-running-p) (server-start))

(defalias 'view-emacs-news 'ignore)
(defalias 'describe-gnu-project 'ignore)
(use-package keychain-environment
:config
(keychain-refresh-environment))

;; org mode
(use-package org
  :ensure t
  :defer t
  :commands (org-mode org-version)
  :init
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (latex . t)
     (sql . t)
     (lisp . t)))
  (font-lock-add-keywords 'org-mode
                          '(("^ +\\([-*]\\) "
                             (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
  :mode
  ("\\.org\\'" . org-mode)
  :hook
  (org-mode . visual-line-mode)
  :config
  (add-to-list 'org-structure-template-alist
               '("b" . "abstract"))
  (setq org-src-fontify-natively t
        org-hide-emphasis-markers t
        org-src-1tab-acts-natively t)
  (setq org-capture-templates
        '(("n" "Notes"
           entry (file+headline "notes.org" "Notes")
           "- %?\n %U")
          )))
;; addition key definitions for org
(keymap-global-set "C-c l" 'org-store-link)
(keymap-global-set "C-c c" 'org-capture)

(use-package org-bullets
  :hook
  (org-mode . org-bullets-mode))

(use-package org-appear
  :commands (org-appear-mode)
  :hook
  (org-mode . org-appear-mode)
  :config
  (setq org-appear-autoemphasis t
        org-appear-autolinks t
        org-appear-autosubmarkers t))

(use-package toc-org
  :hook ((org-mode . toc-org-mode)))

(use-package pikchr-mode
  :config
  (require 'xml))

(use-package vc-fossil)

(use-package markdown-mode
  :hook ((markdown-mode . visual-line-mode)))

(use-package adoc-mode
  :ensure t
  :config
  (add-to-list 'auto-mode-alist (cons "\\.adoc\\'" 'adoc-mode)))

(add-hook 'after-init-hook #'save-place-mode)

(add-hook 'after-init-hook #'(lambda()
                               (let ((inhibit-message t))
                                 (recentf-mode 1))))
(add-hook 'kill-emacs-hook #'recentf-cleanup)

(add-hook 'before-save-hook 'whitespace-cleanup)
(setq show-paren-delay 0)
(show-paren-mode t)
(electric-pair-mode t)
;(setq show-paren-style 'mixed)     ;mixed, parenthesis, expression
(setq show-paren-style 'expression)

(use-package rainbow-delimiters
  :hook ((prog-mode . rainbow-delimiters-mode)))

(use-package paredit
  :hook
  ((emacs-lisp-mode . paredit-mode)
   ;(elm-mode . paredit-mode)
   ;(haskell-mode . paredit-mode)
   (lisp-mode . paredit-mode)
   (lisp-interactive . paredit-mode)))

(defun my-dired-mode-hook ()
  (put 'dired-find-alternate-file 'disabled nil) ; Disables the warning.
  (define-key dired-mode-map (kbd "RET") 'dired-find-alternate-file)
  (define-key dired-mode-map (kbd "^") 'dired-up-directory-same-buffer))

(setq dired-use-ls-dired nil
      dired-listing-switches "-alh --group-directories-first -t -o --time-style=long-iso")
(setq dired-use-ls-dired nil)
(keymap-global-set "C-x C-d" 'dired)

(use-package ispell
  :ensure nil
  :defer t
  :commands (ispell ispell-minor-mode)
  :custom
  ;; Set the ispell program name to aspell
  (ispell-program-name "aspell")

  ;; Configures Aspell's suggestion mode to "ultra", which provides more
  ;; aggressive and detailed suggestions for misspelled words. The language
  ;; is set to "en_US" for US English, which can be replaced with your desired
  ;; language code (e.g., "en_GB" for British English, "de_DE" for German).
  (ispell-extra-args '("--sug-mode=ultra" "--lang=en_US")))

(setq modus-themes-mode-line '(accented borderless)
      modus-themes-italic-constructs t
      modus-themes-fringes 'subtle
      modus-themes-tabs-accented t
      modus-themes-paren-math '(bold intense)
      modus-themes-prompts '(bold intense)
      modus-themes-scale-headings t
      modus-themes-region '(bg-only)
      modus-themes-headings
      '((1 . (rainbow overline background 1.4))
        (2 . (rainbow background 1.3))
        (3 . (rainbow bold 12))
        (t . (semilight 1.1))))

(use-package modus-themes
  :init
  (load-theme 'modus-vivendi t)
  ;;(load-theme 'modus-operandi-tinted t)
  :config
  (set-face-attribute 'default nil
      :font "Fira Code Retina"
      :height 100)
  (set-face-attribute 'fixed-pitch nil
      :font "Fira Code Retina"
      :height 100)
  (set-face-attribute 'variable-pitch nil
      :font "Cantarell"
      :height 100
      :weight 'regular)
  )

;; Enable the www ligature in every possible major mode
(use-package ligature
  :config
  (ligature-set-ligatures 't '("www"))
  (global-ligature-mode 't)
  ;; Enable ligatures in programming modes
  (ligature-set-ligatures
   '(prog-mode adoc-mode org-mode)
   '("www" ":=" "!!" "!=" "!==" "-}"
     "----" "-->" "->" "->>" "-<" "-<<" "-~"
     "#{" "#[" "##" "###" "####" "#(" "#?" "#_"
     "#_(" ".-" ".=" ".." "..<" "..." "?=" "??"
     ";;" "/*" "/**" "/=" "/==" "/>" "//" "///"
     "&&" "||" "||=" "|=" "|>" "^=" "$>" "++"
     "+++" "+>" "=:=" "==>" "=>"
     "=>>" "<=" "=<<" "=/=" ">-" ">=" ">=>"
     ">>" ">>-" ">>=" ">>>" "<*" "<*>" "<|"
     "<|>" "<$" "<$>" "<!--" "<-" "<--" "<->"
     "<+" "<+>" "<=" "<==" "<=>" "<=<" "<>"
     "<<" "<<-" "<<=" "<<<" "<~" "<~~" "</"
     "</>" "~@" "~-" "~>" "~~" "~~>" "%%"))
  )

(setq auto-save-default t
      auto-save-interval 300
      auto-save-timeout 30)

(set-locale-environment "en_US.UTF-8")
(set-default-coding-systems 'utf-8)

;; Treat modules as tcl files.
(add-to-list 'auto-mode-alist '("\\.tm\\'" . tcl-mode))

;;; lilypond
(autoload 'LilyPond-mode "lilypond-mode" "LilyPond Editing Mode" t)
(add-to-list 'auto-mode-alist '("\\.ly\\'" . LilyPond-mode))
(add-to-list 'auto-mode-alist '("\\.ily\\'" . LilyPond-mode))
;; (add-hook 'LilyPond-mode-hook (lambda () (turn-on-font-lock)))

(use-package yasnippet
  :ensure t
  :bind ("C-c y" . yas-expand)
  :config
  (define-key yas-minor-mode-map (kbd "<tab>") nil)
  (define-key yas-minor-mode-map (kbd "TAB") nil)
  (yas-global-mode))

(setq auto-insert-directory "~/.config/emacs/templates/"
      auto-insert-mode t
      auto-insert-query nil
      auto-insert-alist
        '((python-mode . "python.template")
          (sh-mode     . "sh.template")
          (tcl-mode    . "tcl.template")))
(add-hook 'find-file-hook 'auto-insert)

(use-package helpful
  :defer t
  :commands (helpful-callable
             helpful-variable
             helpful-key
             helpful-command
             helpful-at-point
             helpful-function)
  :bind
  ([remap describe-command] . helpful-command)
  ([remap describe-function] . helpful-callable)
  ([remap describe-key] . helpful-key)
  ([remap describe-symbol] . helpful-symbol)
  ([remap describe-variable] . helpful-variable)
  :custom
  (helpful-max-buffers 7))

(use-package copy-as-format
  :ensure t
  :defer t
  :bind
  (("C-c w a" . copy-as-format-asciidoc)
   ("C-c w g" . copy-as-format-github)
   ("C-c w m" . copy-as-format-markdown)
   ("C-c w o" . copy-as-format-org-mode)
   ))

(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1))

(use-package nerd-icons)

(use-package sly
  :config
  (setq inferior-lisp-program "sbcl"))

(use-package yaml-mode)
(use-package typescript-mode
  :config
  (setq typescript-indent-level 2
        typescript-auto-indent-flag t))

(use-package graphql-ts-mode
  :mode ("\\.graphql\\'" "\\.gql\\'")
  :init
  (with-eval-after-load 'treesit
    (add-to-list 'treesit-language-source-alist
                 '(graphql "https://github.com/bkegley/tree-sitter-graphql")))
  )

(use-package js2-mode
  :config
  (setq js2-basic-offset 2))
(use-package json-mode)

(use-package lua-mode
  :ensure t
  :mode "\\.lua\\'"
  :interpreter "lua"
  :config
  (setq lua-indent-level 4)) ; Change indentation depth as preferred

(use-package qml-mode)

(use-package haskell-mode
  :config
  (require 'hs-lint)
  (setq haskell-process-type 'cabal-repl
        haskell-literate 'tex
        haskell-process-suggest-remove-import-lines t
        haskell-stylish-on-save t)
  :hook
  ( ;; (haskell-mode . turn-on-haskell-indentation)
   (haskell-mode . haskell-indentation-mode)
   (haskell-mode . interactive-haskell-mode)
   (haskell-mode . eglot-ensure))
  :bind (:map haskell-mode-map
              ("C-c a c" . haskel-cabal-visit-file)
              ("C-c a i" . haskell-navigate-imports)
              ("C-c a l" . hs-lint)
              ("C-c m" . haskell-compile)
              :map haskell-cabal-mode-map
              ("C-c m" . haskell-compile)))

(use-package lsp-haskell
  :config
  (setq lsp-haskell-server-path "haskell-language-server-wrapper"))

(use-package indent-bars
  :hook
  ((elm-mode . indent-bars-mode))
  :custom
  (indent-bars-no-descend-lists t) ; no extra bars in continued func arg lists
  (indent-bars-treesit-support t)
  (indent-bars-treesit-ignore-blank-lines-types '("module"))
  :config
  (setq
   indent-bars-color '(highlight :face-bg t :blend 0.5)
   indent-bars-pattern "."
   indent-bars-width-frac 0.1
   indent-bars-pad-frac 0.1
   indent-bars-zigzag nil
   indent-bars-color-by-depth nil
   indent-bars-highlight-current-depth nil
   indent-bars-display-on-blank-lines nil)
  )

(use-package elm-mode
  :hook ((elm-mode . eglot-ensure))
  )

(use-package project)

(use-package which-key
  :config
  (which-key-mode))

(use-package dimmer
  :custom (differ-fraction 0.2)
  :custom (dimmer-mode))

;; global revert
(global-auto-revert-mode 1)
(setq global-auto-revert-non-file-buffers t) ;for dired

;; tabs
(setq backward-delete-char-untabify-method 'hungry
      ;; tab-always-indent 'complete
      )
(setq-default tab-width 2
              indent-tabs-mode nil      ; tab inserts spaces
              electric-indent-inhibit t ;
              )

;; Enabled backups to save your changes to a file intermittently
(setq make-backup-files t
      vc-make-backup-files t
      backup-by-copying t
      org-hide-emphasis-markers t
      frame-inhibit-implied-resize t
      pixel-scroll-precision-mode t
      ;;kill-whole-line t
      custom-file (locate-user-emacs-file "custom.el")
      package-install-upgrade-built-in t
      require-final-newline t
      recentf-max-menu-items 10
      use-dialog-box nil
      project-vc-extra-root-markers '("*.cabal"
                                      ".project")
      x-select-enable-clipboard-manager nil
      kept-old-versions 10
      kept-new-versions 10)
(setq-default use-short-answers t       ;
              truncate-lines t
              case-fold-search nil      ; maybe ...
              fill-column 78            ;
              auto-fill-mode t          ; fill paragraphs to fill-column
              auto-fill-function 'do-auto-fill)

(keymap-global-set "C-x ," 'bury-buffer)
(keymap-global-set "M-g" 'goto-line)
(keymap-global-set "C-x t" 'toggle-truncate-lines)
(keymap-global-set "C-x C-r" 'recentf-open-files)
(keymap-global-set "C-x C-b" 'electric-buffer-list)

(setopt confirm-kill-processes nil)

(put 'narrow-to-region 'disabled nil)
(put 'set-goal-column 'disabled nil)

(use-package sudo-edit)

;;(delete-selection-mode t)
(column-number-mode)
